
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef TRICORE_H
#define TRICORE_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "util.h"

typedef struct Tricore__ctx_type_0 {
   uint8_t reset_state;
   float reset_phase;
   float rate;
   float phase;
   uint8_t direction;
   Util__ctx_type_0 _inst451;
   Util__ctx_type_0 _inst351;
   Util__ctx_type_1 _inst13b;
} Tricore__ctx_type_0;

typedef Tricore__ctx_type_0 Tricore_process_type;

void Tricore__ctx_type_0_init(Tricore__ctx_type_0 &_output_);

static_inline void Tricore_process_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

float Tricore_process(Tricore__ctx_type_0 &_ctx, float cv, float reset, float disable);

typedef Tricore__ctx_type_0 Tricore_noteOn_type;

static_inline void Tricore_noteOn_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

static_inline void Tricore_noteOn(Tricore__ctx_type_0 &_ctx, int note, int velocity, int channel){
}

typedef Tricore__ctx_type_0 Tricore_noteOff_type;

static_inline void Tricore_noteOff_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

static_inline void Tricore_noteOff(Tricore__ctx_type_0 &_ctx, int note, int channel){
}

typedef Tricore__ctx_type_0 Tricore_controlChange_type;

static_inline void Tricore_controlChange_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

static_inline void Tricore_controlChange(Tricore__ctx_type_0 &_ctx, int control, int value, int channel){
}

typedef Tricore__ctx_type_0 Tricore_default_type;

static_inline void Tricore_default_init(Tricore__ctx_type_0 &_output_){
   Tricore__ctx_type_0_init(_output_);
   return ;
}

static_inline void Tricore_default(Tricore__ctx_type_0 &_ctx){
   _ctx.rate = 0.759366720147f;
};



#endif // TRICORE_H
